### ISSUE TITLE
Investoscope Updater crashing on one symbol, not updating others. Please add logging

### ISSUE THREAD

**Issue by charlietomo** [Rod-Persky/investoscope-easy-update#8]
I'm having an issue whereby the Investoscope Updater App does not update all the symbols that it used to. It appears to get to one symbol and then just quits (after a split second), and the app does not stay open or give any error message for troubleshooting.

Is there anywhere I can check (manually is fine) a log of what has happened so I can try and fix it? As the Investoscope Updater just quits when it gets to this symbol, it doesn't update a good chunk of my portfolios.

With further investigation this is due to a symbol that has been delisted ([GKN.L](https://finance.yahoo.com/lookup?s=GKN.L)) so it would be good to handle this gracefully rather than stopping the update and having to go troubleshoot manually. Other symbols have also changed, and I am now at the stage I'm not even getting a split-second to view (or screengrab via video) the offending symbol.

Could you add logging and then it would be possible to troubleshoot. Many thanks in advance and thanks again for creating this.

**Comment by Alexandra1105** [comment]
Hi @charlietomo 

I updated the code to stay open for 3 seconds, that's not really helpful for debugging though.

The program should simply skip codes that do not exist as they cause an exception which will be totally ignored.

I was having a similar issue where the program closed immediately due to updating python and not reinstalling the requests library. Perhaps you can check that requests is installed.

I'll look into putting debug output in the temp folder so that it can be inspected in one way or another.

**Comment by Rod-Persky** [comment]
Hi @charlietomo

I updated the code to stay open for 3 seconds, that's not really helpful for debugging though.

The program should simply skip codes that do not exist as they cause an exception which will be totally ignored.

I was having a similar issue where the program closed immediately due to updating python and not reinstalling the requests library. Perhaps you can check that requests is installed.

I'll look into putting debug output in the temp folder so that it can be inspected in one way or another.

**Comment by charlietomo** [comment]
Requests is installed but out of date `You are using pip version 9.0.1, however version 18.0 is available.
`. I have now installed version 18.0. I have seen the 3 second window, which was useful as it showed me which symbol was an issue so I could correct in Investoscope (it was a symbol that had been de-listed). I'm closing this as it's not an issue to me any more, thanks.
